labels: ['feature request']
body:
  - type: dropdown
    id: service
    attributes:
      label: Service
      description: Which streaming service are you suggesting a feature for?
      multiple: false
      options:
        - F1 TV
        - IndyCar
        - NASCAR
        - WEC
        - Other
    validations:
      required: true

  - type: textarea
    attributes:
      label: "What's your idea?"
      description: |
        Share your idea for a new feature or improvement! This space is for **open-ended conversations** to help shape the future of the project.
    
        Be as descriptive and specific as possible. If you're requesting a visual change or implementation, please provide a screenshot of the interface you'd like to have changed.
    
        If you have multiple ideas, please split them in separate feature requests.
    validations:
      required: true
