name: Bug Report
description: File a bug report.
labels: ["bug"]
assignees: ["f1multiviewer", "jeppeolesen", "LapsTimeOFF"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report. Please use a descriptive title that clearly summarizes the issue.
        
        A good title helps us quickly understand the nature of the bug and prioritize it. Try to include what’s broken and where it happens — for example: "Streams stuck on loading screen on Windows 11" instead of just "MultiViewer is not working".
  
  - type: dropdown
    id: service
    attributes:
      label: Service
      description: Which streaming service are you reporting a bug for?
      multiple: false
      options:
        - F1 TV
        - IndyCar
        - NASCAR
        - WEC
        - Other
    validations:
      required: true

  - type: dropdown
    id: subscription
    attributes:
      label: What subscription do you have?
      description: "If you're submitting a bug for a service other than F1 TV, please select N/A"
      multiple: false
      options:
        - F1 TV Access
        - F1 TV Pro
        - F1 TV Premium
        - "I don't have an F1 TV subscription"
        - N/A
    validations:
      required: true
  
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Be as specific as posible. What happened? What were you expecting would happen? What actions did you make to get the bug?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: screeshots
    attributes:
      label: Screenshots
      description: "Please provide screenshots of the issues you're experiencing"
  
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running? (vX.XX.X, you can check it out by pressing the 3 dots on the top right corner of the app)
    validations:
      required: true
  
  - type: input
    id: region
    attributes:
      label: Country
      description: What country are you in? (e.g. UK, Germany, France, etc.)
    validations:
      required: true
  
  - type: dropdown
    id: os
    attributes:
      label: What operating system are you using?
      multiple: false
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true
  
  - type: input
    id: os-version
    attributes:
      label: OS Version
      description: What version of your operating system are you using? (e.g. Windows 11, Windows 10, macOS Sequoia, Debian, etc.)
    validations:
      required: true
  
  - type: textarea
    id: troubleshooting
    attributes:
      label: Troubleshooting payload
      description: Open the troubleshooting page (Bottom left -> Troubleshooting or [click here](https://muvi.gg/troubleshooting) after opening the MultiViewer app). On that page, press `C`, it will copy some essential debug data to your clipboard, then just paste it in this box. (The data is automatically sanitized of all tokens or personal data before copying it)
      render: shell
