blank_issues_enabled: false
contact_links:
  - name: MultiViewer's Discord
    url: https://muvi.gg/discord
    about: Our support team is more active on Discord. Please join us there for any questions or support.
  - name: Feature request
    url: https://github.com/f1multiviewer/issue-tracker/discussions/new?category=ideas
    about: For ideas or feature requests
  - name: MultiViewer Documentation
    url: https://multiviewer.app/docs
    about: View the documentation
